create table if not exists public.clickup_delivery_history (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  webhook_id text not null,
  history_item_id text not null,
  task_id text not null,
  task_name text not null,
  task_url text,
  list_id text not null,
  professional text not null check (professional in ('patricia', 'anna')),
  status_before text not null,
  status_after text not null,
  changed_at timestamptz not null,
  changed_by_id text,
  changed_by_name text,
  due_at timestamptz,
  due_has_time boolean not null default false,
  deadline_result text not null check (deadline_result in ('on_time', 'late', 'no_due_date')),
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists clickup_delivery_history_professional_changed_at_idx
  on public.clickup_delivery_history (professional, changed_at desc);

alter table public.clickup_delivery_history enable row level security;

drop policy if exists "Authenticated users can read delivery history"
  on public.clickup_delivery_history;

create policy "Authenticated users can read delivery history"
  on public.clickup_delivery_history
  for select to authenticated
  using (true);

revoke insert, update, delete on public.clickup_delivery_history from anon, authenticated;
grant select on public.clickup_delivery_history to authenticated;
